# Generated by Django 3.0.3 on 2020-02-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudreads', '0002_auto_20200210_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='booklist',
            name='book_rating',
        ),
        migrations.AddField(
            model_name='booklist',
            name='book_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
