# Generated by Django 3.0.3 on 2020-02-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudreads', '0003_auto_20200211_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='book_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
