# Generated by Django 3.0.3 on 2020-02-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudreads', '0004_booklist_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='book_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booklist',
            name='book_description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='booklist',
            name='book_image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
