# Generated by Django 3.0.3 on 2020-02-12 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudreads', '0005_auto_20200212_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='book_was_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date.today),
            preserve_default=False,
        ),
    ]
