# Generated by Django 3.0.3 on 2020-02-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gudreads', '0006_auto_20200212_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='book_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
