# Generated by Django 3.0.3 on 2020-02-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gudreads', '0007_booklist_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='book_id',
        ),
    ]
